[development]
ServerAddr = "192.168.50.4"
Port = 8181
UploadAddrPattern = "/upload"
ServerFilesLocation = "./files/"
FileDbJsonPath = "./filedb.json"
SyncRoot = "$GOPATH/src/github.com/tonychol/sink/testDir"
BufferSize = 1024
FreeSocketPattern = "/socketPort"


[production]
ServerAddr = "http://localhost"
Port = 80
UploadAddrPattern = "/upload"
ServerFilesLocation = "./files/"
FileDbJsonPath = "./filedb.json"
SyncRoot = "$GOPATH/src/github.com/tonychol/sink/testDir"
BufferSize = 1024
FreeSocketPattern = "/socketPort"