[development]
ServerAddr = "http://localhost"
Port = 8181
UploadAddrPattern = "/upload"
ServerFilesLocation = "./files/"
FileDbJsonPath = "./filedb.json"
SyncRoot = "$GOPATH/src/github.com/tonychol/sink/testDir"