[development]
ServerAddr = "http://localhost"
Port = 8182
UploadAddrPattern = "/upload"
ServerFilesLocation = "./files/"
FileDbJsonPath = "./filedb.json"
SyncRoot = "$GOPATH/src/github.com/tonychol/sink/testDir"
BufferSize = 1024


[production]
ServerAddr = "http://localhost"
Port = 80
UploadAddrPattern = "/upload"
ServerFilesLocation = "./files/"
FileDbJsonPath = "./filedb.json"
SyncRoot = "$GOPATH/src/github.com/tonychol/sink/testDir"
BufferSize = 1024